export const LORE_TEXT = `
Dicen que todo mundo tiene un fondo. Los hombres levantan templos para contemplar los cielos y excavan tumbas para ocultar a sus muertos, como si entre las alturas y las profundidades pudieran encerrar los límites de aquello que llaman realidad. Durante generaciones han buscado el principio de las cosas en las estrellas y su final bajo la tierra, convencidos de que basta con mirar suficientemente lejos o cavar suficientemente profundo para encontrar los límites de su existencia. Pero hay profundidades que ninguna pala puede alcanzar y cielos que ningún ojo debería contemplar, porque debajo de todo aquello que conocemos existe algo más; no debajo de la tierra, ni debajo de las montañas, ni debajo de las ruinas de los hombres, sino debajo del mundo. Existe una profundidad que no pertenece al espacio, sino a la existencia misma, un estrato oscuro donde las cosas pierden los nombres que alguna vez les fueron dados y comienzan a revelar formas más antiguas que su propia memoria. Los pocos sabios que han sospechado su existencia le han dado nombres diferentes: abismo, infierno, sueño, olvido; pero ninguno de ellos parece suficiente. Un infierno puede tener fuego, y allí abajo puede no haberlo; un sueño puede desaparecer al despertar, y aquello que yace debajo no desaparece; el olvido puede borrar un nombre, pero en el Below hay cosas que parecen existir precisamente porque fueron olvidadas. Quizá el Below sea el lugar donde termina una realidad, el último estrato de aquello que un ser puede comprender antes de alcanzar algo que se encuentra más allá de su mundo; o quizá sea, por el contrario, el lugar donde comienza otra realidad, una profundidad que no se encuentra debajo de nuestros pies sino debajo de aquello que creemos ser.

Hay mundos que nacen de la materia y otros que nacen de aquello que alguna vez fue un ser. Los que han trascendido pueden levantar cielos donde antes no había cielos, formar tierras que obedecen a leyes que ningún mortal conoció y dar refugio a los muertos dentro de dominios que son, en cierto modo, extensiones de quienes los crearon. Así aparecen los lugares que aguardan a los muertos, realidades que no son necesariamente cielos ni prisiones, sino mundos nacidos de una existencia que ha alcanzado una condición distinta. Y si una realidad puede tener un creador, también puede tener profundidades que su creador no comprende; porque quizá aquello que un ser crea termina convirtiéndose en algo que existe más allá de su voluntad, y quizá incluso una entidad capaz de levantar un mundo pueda descubrir que ese mundo posee un fondo que nunca contempló. Tal vez incluso los dioses tengan algo debajo de ellos. Tal vez toda eternidad esconda una puerta. Y tal vez detrás de esa puerta exista un lugar donde incluso los dioses puedan recordar lo que significa tener miedo.

Fue hacia ese lugar donde descendió **THE WITNESS**. Nadie sabe desde dónde vino, nadie recuerda haberlo visto antes del descenso y ni siquiera está claro que Witness sea realmente un nombre. Quizá sea un título, quizá una condena, quizá aquello que queda de un ser cuando ya no puede hacer otra cosa que contemplar. No sabemos qué buscaba, ni qué esperaba encontrar, ni si alguna vez comprendió realmente hacia dónde se dirigía. Solo sabemos que descendió y siguió descendiendo, mientras el mundo que conocía comenzaba lentamente a perder sus formas conocidas. Al principio todavía existían cosas que podían reconocerse: piedra, oscuridad, movimiento, distancia; pero cuanto más abajo penetraba, más extrañas se volvían las proporciones del lugar. Las distancias dejaron de comportarse como distancias, las sombras parecían poseer una profundidad propia y había corredores que parecían extenderse durante siglos y, sin embargo, terminaban detrás de la misma puerta. Había espacios demasiado grandes para contenerse dentro de sí mismos y lugares cuya oscuridad parecía ocupar más espacio del que físicamente podían contener. Hubo momentos en que THE WITNESS tuvo la desagradable impresión de que no estaba descendiendo, sino que era el mundo el que estaba descendiendo alrededor de él, como si la realidad que había conocido estuviera hundiéndose lentamente mientras él permanecía en su centro, contemplando cómo las últimas certezas se deshacían.

Entonces aparecieron los primeros fragmentos. Eran pequeñas formas que se movían en la oscuridad, separadas y errantes, como si hubieran sido arrancadas de algo mucho mayor y condenadas a buscarse eternamente sin recordar qué era aquello que habían perdido. Durante un tiempo THE WITNESS las contempló como criaturas independientes, pero pronto descubrió que la separación no parecía ser una condición permanente para ellas. Se encontraban y, al encontrarse, no permanecían siendo lo que eran. Tres podían convertirse en un grupo, un grupo podía convertirse en un nido y un nido podía convertirse en una masa, mientras la distancia entre unas formas y otras desaparecía poco a poco hasta que resultaba imposible determinar dónde terminaba una criatura y comenzaba la siguiente. Y cuando aquella masa alcanzaba cierto límite ocurría algo que THE WITNESS no sabía nombrar: la carne se reunía, las formas se mezclaban, los límites se borraban y aquello que surgía ya no parecía ser una multitud, sino **una sola cosa que había aprendido a ser muchas**. Una ABERRATION. Desde entonces, THE WITNESS comprendió que aquellas criaturas no estaban simplemente creciendo; estaban cambiando, y en aquel lugar cambiar no significaba necesariamente convertirse en algo mejor, ni alcanzar una forma superior, sino abandonar aquello que alguna vez se había sido para convertirse en algo que quizá nunca había existido antes.

Más abajo escuchó voces. No eran voces humanas y no hablaban en ninguna lengua que pudiera reconocer, pero había en ellas algo que se parecía demasiado al recuerdo de una canción, como si una melodía antiquísima hubiera sobrevivido a quienes alguna vez la cantaron y ahora recorriera la oscuridad buscando una garganta que ya no existía. Una multitud de gargantas vacías se elevaba desde las profundidades, un coro sin músicos, una melodía sin origen, y THE WITNESS no comprendió qué cantaban, pero sintió que aquellas voces no estaban destinadas a ser escuchadas. Sintió que estaban llamando y, durante un instante terrible, tuvo la certeza de que no estaban llamando a algo que se encontraba lejos, sino a algo que ya estaba allí. Después encontró una boca, y más adelante un ojo, y después algo que parecía observar incluso cuando no tenía ojos. Cuanto más descendía, más difícil resultaba distinguir entre las criaturas y el lugar que las había engendrado, pues las formas parecían pertenecer a la oscuridad del mismo modo en que la oscuridad parecía pertenecerles a ellas. Quizá el Below estaba lleno de seres; o quizá aquellas criaturas eran simplemente las heridas de una realidad que estaba intentando tomar forma. Tal vez el Enjambre no era una población que habitaba aquel lugar, sino una de las maneras en que aquel lugar podía manifestarse. THE WITNESS no podía saberlo, porque cuanto más observaba, menos claro resultaba dónde terminaba una criatura y dónde comenzaba el mundo que la rodeaba.

Y entonces apareció **TAYATNA**. No llegó, no descendió, no emergió de ninguna parte; simplemente estaba allí, como si hubiese permanecido esperando desde antes de que THE WITNESS aprendiera a caminar, desde antes incluso de que aquel descenso tuviera un principio que pudiera ser recordado. Su presencia era distinta a la de todo aquello que había encontrado. No poseía la violencia ciega de las criaturas, no necesitaba perseguir ni demostrar su fuerza, porque había en ella algo mucho más antiguo y mucho más insoportable: una tristeza tan profunda que parecía haber olvidado el objeto de su propia tristeza. TAYATNA, la pena, la tristeza, una manifestación de ɨnkalanpat. Y al contemplarla, THE WITNESS comprendió algo que ninguna criatura del Below había podido enseñarle: que la muerte no era la única forma de perder algo. Se puede perder un mundo sin destruirlo, se puede perder un nombre mientras la criatura que lo llevaba continúa caminando, se puede perder una vida mucho antes de que el cuerpo muera y se puede perder aquello que uno fue sin dejar de existir. Quizá existen pérdidas tan antiguas que ningún ser vivo recuerda haberlas sufrido; quizá TAYATNA es el recuerdo de una de ellas, o quizá es la tristeza misma contemplada desde un lugar donde las emociones ya no pertenecen a ningún individuo y la pena puede existir sin necesitar un rostro que la sienta. THE WITNESS no lo supo y tal vez nunca lo sabrá, porque cuando la miró tuvo por primera vez la sensación de que el descenso no había sido hacia TAYATNA, sino hacia sí mismo.

Entonces comprendió por qué el Below parecía tan familiar. No era porque hubiese estado allí antes, sino porque algunas profundidades no necesitan ser conocidas para pertenecernos. Todo ser guarda algo debajo de sí: una habitación cerrada, una memoria sin nombre, una criatura que jamás llegó a nacer, un miedo que no recuerda haber aprendido, un mundo que alguna vez pudo haber sido. Y si los dioses pueden crear realidades, si los muertos pueden despertar dentro de ellas, si un ser puede trascender hasta convertirse en el fundamento de un mundo, entonces quizá ningún mundo sea realmente el último. Quizá debajo de cada cielo exista otro cielo, debajo de cada muerte otra forma de existencia y debajo de cada dios algo que el dios mismo no puede contemplar. Quizá el fondo no sea un lugar al que finalmente se llega, sino solamente el nombre que damos al límite de aquello que todavía somos capaces de comprender. Y debajo de todo aquello que creemos ser, debajo de nuestros recuerdos, de nuestros nombres, de nuestros cuerpos y de nuestras propias realidades, quizá exista todavía algo que espera.

THE WITNESS permaneció frente a TAYATNA. Por un instante no hubo criaturas, no hubo oscuridad, no hubo arriba ni abajo; solo dos seres contemplándose en un lugar donde la realidad parecía haber olvidado cuál de los dos era el que estaba siendo observado. Y entonces surgió una pregunta, no una pregunta que alguien hubiese pronunciado ni una pregunta que pudiera responderse con palabras, sino una pregunta que parecía haber estado allí desde antes del descenso, aguardando en la oscuridad a que alguien llegara lo suficientemente lejos para escucharla.

**¿Qué tuvo que perderse para que este lugar existiera?**

Y detrás de ella apareció otra, más pequeña, más íntima y mucho más terrible.

**¿Qué está perdiendo THE WITNESS mientras mira?**
`;